import { Box, Button, HStack, Link } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'focus-visible/dist/focus-visible';
import PostForm from '../components/textArea';
import PostPreview from '../components/previewArea';
import Appbar from '../components/Appbar';
import ReactMarkdown from "react-markdown";
import { NavContent } from '../components/chakra/NavbarWithSubmenu/NavContent';
import { FirebaseApp, getApp } from 'firebase/app';


export default function Home() {
  const app: FirebaseApp = getApp()
  return (
    <div className={styles.container}>
      <Head>
        <title>日記</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Appbar></Appbar> */}
      <NavContent.Desktop></NavContent.Desktop>
      {/* <Box >
        <PostForm />
      </Box> */}
      <ul>
        <li>name = {app.name}</li>
        <li>appId = {app.options.appId}</li>
        <li>apiKey = {app.options.apiKey}</li>
      </ul>
    </div>
  )
}
