import { Box, Button, HStack } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'focus-visible/dist/focus-visible';
import PostForm from '../components/textArea';
import PostPreview from '../components/previewArea';
import Appbar from '../components/Appbar';
import ReactMarkdown from "react-markdown";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>マークダウンくん</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Appbar></Appbar>
      <Box >
        <PostForm />
      </Box>


    </div>
  )
}
