import {
  Avatar,
  Box,
  Button,
  Center,
  Heading,
  HStack,
  Link,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "focus-visible/dist/focus-visible";
import PostForm from "../components/textArea";
import PostPreview from "../components/previewArea";
import Appbar from "../components/Appbar";
import ReactMarkdown from "react-markdown";
import { NavContent } from "../components/chakra/NavbarWithSubmenu/NavContent";
import { FirebaseApp, getApp } from "firebase/app";
import { NavbarWithAvator } from "../components/chakra/NavbarWithAvatar/App";

export default function Home() {
  const app: FirebaseApp = getApp();
  return (
    <>
      <Head>
        <title>Vオシ！</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box bgColor={"aliceblue"}>
        <Box h={"100vh"}>
          <NavbarWithAvator></NavbarWithAvator>
          <Center h={"100px"}>
            <Heading>ここおすと移動</Heading>
            <Avatar
              boxSize="10"
              name="Christoph Winston"
              src="https://tinyurl.com/yhkm2ek8"
              as="a"
              href="/VtuberCommunityPage"
            ></Avatar>
          </Center>
        </Box>
      </Box>
    </>
  );
}
