import {
  Avatar,
  Box,
  Button,
  Center,
  Heading,
  HStack,
  Link,
  Image,
  InputGroup,
  Input,
  InputRightElement,
  VStack,
  Text,
} from "@chakra-ui/react"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import "focus-visible/dist/focus-visible"
import PostForm from "../components/textArea"
import PostPreview from "../components/previewArea"
import Appbar from "../components/Appbar"
import ReactMarkdown from "react-markdown"
import { NavContent } from "../components/chakra/NavbarWithSubmenu/NavContent"
import { FirebaseApp, getApp } from "firebase/app"
import { NavbarWithAvator } from "../components/chakra/NavbarWithAvatar/App"
import VtuberIconCard from "../components/Cards/idea-card/VtuberIconCard"
import YouTube from "react-youtube"
import ArticleCard from "../components/Cards/idea-card/ArticleCard/app"

export default function Home() {
  const app: FirebaseApp = getApp()

  const h = "250px"

  return (
    <>
      {/* https://www.googleapis.com/youtube/v3/channels?part=snippet&id=UC9xRxuzPaWS5vgrlH9436rQ&key=AIzaSyAP7sERAjo5k_SlyPs_gIM6UOF40ImgOig */}
      <Head>
        <title>VOSHI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box bgColor={"aliceblue"}>
        <NavbarWithAvator></NavbarWithAvator>
        <VStack mb='150px' bgColor={""}>
        <Heading textAlign={"left"} mb="30px">COMMUNITY</Heading>
          <Center m={"auto 0"} >
            <HStack>
              <ArticleCard></ArticleCard>
              <ArticleCard></ArticleCard>
              <ArticleCard></ArticleCard>
            </HStack>
          </Center>
        </VStack>

        <Box w='100%' bgColor={"#fa709a"} py='6'>
          <VStack h='' p={""} w='80%' m={"0 auto"}>
            <Heading mb='5' color={"white"} fontSize='40px'>
              話題のVtuber
            </Heading>
            <HStack justifyContent={"space-between"}>
              <VtuberIconCard></VtuberIconCard>
              <VtuberIconCard></VtuberIconCard>
              <VtuberIconCard></VtuberIconCard>
            </HStack>
          </VStack>
        </Box>

        <Box h={"100px"}></Box>
        <Box h='' p={2} w='80%' m={"0 auto"}>
          <Heading mb='5'>話題のVtuber</Heading>
          <HStack justifyContent={"space-between"}>
            <Image
              borderRadius={"50px"}
              h={"300px"}
              w='300px'
              bgSize='inherit'
              src={
                "https://yt3.ggpht.com/ytc/AKedOLQZ7kGnEH7CsX4Eoe79iPVh6Vp6oa2iP3_kInXO=s800-c-k-c0x00ffffff-no-rj"
              }
              alt='a'
            ></Image>
            <Image
              borderRadius={"50px"}
              h={"300px"}
              w='300px'
              bgSize='inherit'
              src={
                "https://yt3.ggpht.com/BcgqkZ7KsqPj6dIT0NIHWqOLt8XcogzwdI5miNwr412ocSwGP057XIy8-ji9kk_hp6MuKPpW4w=s800-c-k-c0x00ffffff-no-rj"
              }
              alt='a'
            ></Image>
            <Image
              borderRadius={"50px"}
              h={"300px"}
              w='300px'
              bgSize='inherit'
              src={
                "https://yt3.ggpht.com/BcgqkZ7KsqPj6dIT0NIHWqOLt8XcogzwdI5miNwr412ocSwGP057XIy8-ji9kk_hp6MuKPpW4w=s800-c-k-c0x00ffffff-no-rj"
              }
              alt='a'
            ></Image>
            <Image
              borderRadius={"50px"}
              h={"300px"}
              w='300px'
              bgSize='inherit'
              src={
                "https://yt3.ggpht.com/BcgqkZ7KsqPj6dIT0NIHWqOLt8XcogzwdI5miNwr412ocSwGP057XIy8-ji9kk_hp6MuKPpW4w=s800-c-k-c0x00ffffff-no-rj"
              }
              alt='a'
            ></Image>
          </HStack>
        </Box>
      </Box>
    </>
  )
}
